package com.stars.modules;

/**
 * Created by zhaowenshuo on 2016/10/22.
 */
public class MConst {

    /* Module Name */
    public static final String Login = "login"; // demo登录
    public static final String Data = "data"; // 通用配置数据commondefine表
    public static final String Gm = "gm"; // gm命令
    public static final String Role = "role"; // 人物
    public static final String Name = "name"; //
    public static final String Tool = "tool"; // 道具
    public static final String Skill = "skill"; // 技能
    public static final String Scene = "scene"; // 场景
    public static final String Dungeon = "dungeon"; // 关卡
    public static final String Drop = "drop"; // 掉落
    public static final String Task = "task"; // 任务
    public static final String Title = "title"; // 称号
    public static final String Induct = "induct"; // 引导
    public static final String Chat = "chat"; // 聊天
    public static final String SkyTower = "skytower"; // 镇妖塔
    public static final String Daily = "daily"; // 活跃度或者日常
    public static final String Email = "email"; // 邮件
    public static final String Friend = "friend"; // 好友
    public static final String ArroundPlayer = "arroundplayer"; // 周围玩家
    public static final String Buddy = "buddy"; // 伙伴
    public static final String SearchTreasure = "searchtreasure"; // 仙山夺宝
    public static final String Rank = "rank"; // 排行榜
    public static final String Family = "family"; // 家族
    public static final String FamilyActExpe = "family.act.expedition"; // 家族活动:
    // 家族远征
    public static final String FamilyActBonfire = "family.act.bonfire"; // 家族篝火
    public static final String FamilyActInvade = "family.act.invade"; // 家族活动:家族入侵
    public static final String FamilyActTreasure = "family.act.treasure";// 家族活动：家族探宝
    public static final String FamilyActWar = "family.act.war"; // 家族活动:家族战
    public static final String FamilyActEscort = "family.act.escort"; // 家族活动:运镖
    public static final String Pk = "pk"; // pk
    public static final String GameCave = "gamecave"; // 洞府
    public static final String Shop = "shop"; // 商店系统
    public static final String CallBoss = "callboss"; // 召唤boss
    public static final String RelationOperation = "relationoperation"; // 关系操作面板
    public static final String Trump = "trump"; // 法宝
    public static final String Team = "team"; // 组队
    public static final String Ride = "ride"; // 坐骑
    public static final String Mind = "mind"; // 心法(经脉)
    public static final String Fashion = "fashion"; // 时装
    public static final String LootTreasure = "loottreasure"; // 野外夺宝
    public static final String OfflinePvp = "offlinepvp"; // 离线pvp(演武场)
    public static final String Achievement = "achievement"; // 成就
    public static final String ForeShow = "foreshow";// 系统预告
    public static final String GEM = "gem"; // 宝石系统;
    public static final String FightingMaster = "fightingmaster";
    public static final String NewEquipment = "newequipment";// 新装备系统
    public static final String SignIn = "signin";// 签到系统
    public static final String RedPoint = "redpoint";// 红点
    public static final String BravePractise = "bravepractise"; // 勇者试炼
    public static final String MasterNotice = "masternotice"; // 皇榜悬赏
    public static final String TeamDungeon = "teamdungeon";// 组队副本
    public static final String ServerLog = "serverlog";// 业务日志
    public static final String Marry = "marry"; // 结婚
    public static final String OperateActivity = "operateactivity"; // 运营活动
    public static final String OnlineReward = "onlinereward"; // 在线奖励活动
    public static final String RetrieveReward = "retrievereward"; // 奖励找回活动
    public static final String SevenDayGoal = "sevendaygoal"; // 七日目标活动
    public static final String NewServerRank = "newserverrank"; // 新服冲级活动
    public static final String NewServerSign = "newserversign"; // 新服签到活动
    public static final String TeamPVPGame = "teampvpgame";// 组队pvp
    public static final String Deity = "deity"; // 神兵;
    public static final String Escort = "escort"; // 运镖
    public static final String Vip = "vip";// vip(贵族)
    public static final String Authentic = "authentic";// 鉴宝系统
    public static final String Guest = "guest";
    public static final String HotUpdate = "hotUpdate"; // 热更模块(处理线上问题)
    public static final String NewServerMoney = "newservermoney";// 新服活动-撒钱
    public static final String NewServerFightScore = "newserverfightscore";// 新服活动-冲战力
    public static final String Gameboard = "gameboard";// 游戏公告
    public static final String Poem = "poem";// 诗集系统
    public static final String NewRedbag = "newredbag"; // 新家族红包
    public static final String EliteDungeon = "elitedungeon"; // 精英副本
    public static final String Cg = "cg"; // Cg动画;
    public static final String NewOfflinePvp = "newofflinepvp";// 新竞技场
    public static final String WordExchange = "wordExchange";// 集字活动
    public static final String OpActFamilyFightScore = "opActFamilyFightScore";// 家族战力冲榜
    public static final String OpActFightScore = "opActFightScore";// 个人战力冲榜
    public static final String ChargeBack = "chargeBack";// 充值返利
    public static final String FirstCharge = "firstCharge";// 首充活动
    public static final String ServerFund = "serverFund";// 开服基金
    public static final String SpecialAccount = "specialAccount";// 特殊账户
    public static final String EverydayCharge = "everydayCharge";// 每日首充
    public static final String PopUp = "popUp";// 登陆弹窗系统
    public static final String Push = "push"; // 精准推送
    public static final String FamilyTask = "familyTask"; // 家族任务
    public static final String DailyCharge = "dailyCharge"; // 日累计充值活动
    public static final String SendVigour = "sendVigour"; // 送体力活动
    public static final String ChargePref = "chargePref"; // 充值特惠
    public static final String WelfareAccount = "welfareAccount"; // 福利号
    public static final String GiftCome520 = "giftCome520"; // 福利号
    public static final String BestCP520 = "bestCP520"; // 最佳组合
    public static final String DragonBoat = "dragonBoat"; // 赛龙舟
    public static final String Quwudu = "quwudu"; // 驱五毒
    public static final String OperateCheck = "operateCheck"; // CD检测
    public static final String OpActChargeScore = "opActChargeScore";// 充值榜
    public static final String OpActKickBack = "opActKickBack";// 消费返利
    public static final String Raffle = "raffle";// 元宝抽奖
    public static final String PoemDungeon = "poemDungeon";// 诗歌副本
    public static final String TencentVideo = "tecentvideo";// 腾讯视频合作活动
    public static final String WeeklyCharge = "weeklyCharge"; // 周累计充值活动
    public static final String SkyRank = "skyRank"; // 天梯排行
    public static final String Book = "book";        // 典籍
    public static final String ChargeGift = "chargeGift"; // 充值送礼
    public static final String Daily5v5 = "daily5v5";// 日常5v5
    public static final String DiscountGift = "discountGift"; // 优惠豪礼
    public static final String ChangeJob = "changeJob"; // 转职
    public static final String OnlyClientShow = "onlyClientShow";//只是为了下发活动数据，服务端并没有对应的活动模块
    public static final String Archery = "archery"; // 射箭小游戏
    public static final String TrueName = "trueName"; // 实名认证
    public static final String CustomerService = "customerService"; // 客服服务vip发邮件
    public static final String OpActBenefitToken = "opActBenefitToken"; // 符文装备体验副本
    public static final String ActiveWeapon = "activeWeapon"; // 活跃神兵
    public static final String FriendShare = "friendShare"; // 朋友圈分享
    public static final String FriendInvite = "friendInvite"; // 好友邀请
    public static final String LevelSpeedUp = "levelSpeedUp"; // 等级加速
    public static final String GetWay = "getWay"; // 获取途径
    public static final String PositionSync = "positionSync"; // 位置同步
    public static final String WeeklyGift = "weeklyGift";
    public static final String CountDown = "CountDown"; //活动预告(倒计时)
    public static final String RuneDungeon = "runeDungeon"; // 符文副本 挑战副本
    public static final String Camp = "camp"; // 阵营
    public static final String NewDailyCharge = "newDailyCharge";
    public static final String GuardOfficial = "guardOfficial";
    public static final String LuckyTurnTable = "luckyTurnTable";
    public static final String OldPlayerBack = "oldPlayerBack";//老玩家回归
    public static final String OpActSecondKill = "opActSecondKill"; //限时抢购
    public static final String Baby = "baby";//宝宝系统
    public static final String Refine = "refine";//杂物回收
    public static final String LuckyDraw = "luckyDraw";//幸运抽奖
    public static final String DareGod = "dareGod";//挑战女神
    public static final String LuckyDraw1 = "luckyDraw1";
    public static final String LuckyDraw2 = "luckyDraw2";
    public static final String LuckyDraw3 = "luckyDraw3";
    public static final String LuckyDraw4 = "luckyDraw4";
    public static final String NewFirstRechargeModule = "newFirstRechargeModule";//新首充每日活动
    public static final String NewFirstRechargeModule1 = "newFirstRechargeModule1";//新首充每日活动(登陆)
    public static final String CollectPhone = "collectPhone";//手机号码收集
    public static final String MoonCake = "MoonCake";//月饼小游戏
    public static final String LuckyCard = "luckyCard";//幸运卡牌
    public static final String FashionCard = "fashionCard";//变身卡
    public static final String ScoreFight = "scoreFight";//战斗积分活动玩法
    public static final String OptionalBox = "toolChoose";//道具自选
    public static final String Soul = "soul";//元神系统

    public static final int CCEquipment = 10500; // 装备
    public static final int CCLogin = 10071; // 登录
    public static final int CCSkyTower = 30000; // 镇妖塔
    public static final int CCSearchTreasure = 10781; // 仙山寻宝
    public static final int CCGameCave = 30560; // 洞府
    public static final int CCMind = 30600; // 心法
    public static final int CCFashion = 30700; // 时装
    public static final int CCLootTreasure = 30130; // 野外夺宝
    public static final int CCBonfire = 10733; // 家族篝火
    public static final int CCAchievement = 30181; // 成就
    public static final int CCFamilyInvade = 30191;// 家族活动:家族入侵
    public static final int CCBravePractise = 30201;// 勇者试炼
    public static final int CCMasterNotice = 30202;// 皇榜悬赏
    public static final int CCGem = 30211; // 宝石;
    public static final int CCOperateActivity = 30300; // 运营活动
    public static final int CCOnlineReward = 30301; // 在线奖励活动
    public static final int CCRetrieveReward = 30302; // 奖励找回活动
    public static final int CCSevenDayGoal = 30303; // 七日目标活动
    public static final int CCNewServerRank = 30304;// 新服冲级活动
    public static final int CCNewServerSign = 30305;// 新服签到活动
    public static final int CCPoem = 30310; // 诗集系统;
    public static final int CCDeity = 30391; // 神兵;
    public static final int CCEliteDungeon = 30392; // 精英副本;
    public static final int CCg = 30671; // CG
    public static final int CCBABY = 31326;//宝宝
}
